package com.project.batacademy.model;
// Generated Aug 5, 2016 1:56:41 PM by Hibernate Tools 4.3.1



/**
 * RegisteredCourses generated by hbm2java
 */
public class RegisteredCourses  implements java.io.Serializable {


     private RegisteredCoursesId id;
     private String courseName;

    public RegisteredCourses() {
    }

    public RegisteredCourses(RegisteredCoursesId id, String courseName) {
       this.id = id;
       this.courseName = courseName;
    }
   
    public RegisteredCoursesId getId() {
        return this.id;
    }
    
    public void setId(RegisteredCoursesId id) {
        this.id = id;
    }
    public String getCourseName() {
        return this.courseName;
    }
    
    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }




}


